version: '3.8'

services:
  app:
    build: .

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - gobot_mongo_data:/data/db
      - ./docker/mongo/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: kikVote

volumes:
  gobot_mongo_data:
